name: Save

on:
  workflow_call:
    inputs:
      commit_message:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Save
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.commit_message }}
          branch: ${{ github.head_ref }}